/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1e2e3439-4cae-43da-851b-3639318ccb9d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_z0jAXNvw1",
    "aws_user_pools_web_client_id": "1mup7prht7360fqtn1rlaor63s",
    "oauth": {}
};


export default awsmobile;
